language: android

android:
  components:
    - build-tools-26.0.1
    - android-26
  licenses:
    - 'android-sdk-license-.+'

before_script:
    - ./gradlew assemble

script:
    - ./gradlew check

jdk:
  - oraclejdk8
